### ISSUE TITLE
Integrate Ruff for Code Formatting and Linting

### ISSUE THREAD

**Issue by andrewendlinger** [HawkMRS/pyAMARES#5]
While working on a Pull Request, I noticed there is no conensus on a coding style / formatter yet.

To enhance code consistency and quality, I propose integrating [Ruff](https://docs.astral.sh/ruff/), an extremely fast Python linter and code formatter.

Happy to help with this :)

### Benefits:
- **Consistent Code Style**: Ensures uniform code formatting across the codebase.
- **Enhanced Readability**: Makes code easier to read and maintain.
- **Automated Error Detection**: Identifies and fixes potential issues automatically.
- **Improved Collaboration**: Facilitates seamless collaboration among contributors.

### Suggested Integration Steps:

1. **Add Ruff to the Project**:
   - **Installation**: Install Ruff as a development dependency.
     ```bash
     pip install ruff
     ```
   - **Configuration**: Create or update the `pyproject.toml` file to configure Ruff's behavior.
     ```toml
     [tool.ruff]
     line-length = 88

     ```
     *Refer to Ruff's [configuration documentation](https://docs.astral.sh/ruff/configuration/) for detailed options.*

2. **Set Up Pre-commit Hook**:

     *This setup will run Ruff's linter and formatter before each commit. You can (and should) also make it part of the CI/CD pipeline. For more details, refer to the [ruff integration doc](https://docs.astral.sh/ruff/integrations/).*

   - **Installation**: Ensure `pre-commit` is installed.
     ```bash
     pip install pre-commit
     ```
   - **Configuration**: Add Ruff to the `.pre-commit-config.yaml` file.
     ```yaml
     repos:
     - repo: https://github.com/astral-sh/ruff-pre-commit
       rev: v0.11.2
       hooks:
         - id: ruff
           args: [--fix]
         - id: ruff-format
     ```

   - **Installation of Hooks**: Install the pre-commit hooks.
     ```bash
     pre-commit install
     ```

3. **Update Documentation**:
   - **README.md**: Add instructions for contributors on how to use Ruff.

### Action Required:
- **Install and configure Ruff** in the project.
- **Format the existing code** in the project.
- **Set up the pre-commit hook** etc. to automate code checks.
- **Update project documentation** to guide contributors on using Ruff.

Integrating Ruff will ensure a consistent and high-quality codebase :)
